# Generated by Django 6.1.1 on 2026-10-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_playlist_remove_cancion_genero_cancion_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='playlist',
            new_name='playlists',
        ),
    ]
