# Generated by Django 6.1.1 on 2026-10-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_cancion_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(max_length=10),
        ),
    ]
