# Generated by Django 6.1.1 on 2026-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_cancion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
